name: Auto Merge PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  instant-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Automatically Merge Pull Request
        run: gh pr merge "${{ github.event.pull_request.html_url }}" --merge --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
